trigger:
  branches:
    include:
      - main

jobs:
  - job: docker

    displayName: "Create docker package for forecaster"

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - bash: |
        echo "##vso[task.setvariable variable=VERSION]$(cat forecaster/__init__.py | cut -d' ' -f 3 | cut -d'"' -f 2)"

    - task: UsePythonVersion@0
      displayName: 'Use Python version'
      inputs:
        versionSpec: '3.8'

    - script: pip install setuptools wheel
      displayName: 'Install dependencies'

    - script: python setup.py bumpver
      displayName: 'Bump dev version'

    - script: python setup.py sdist bdist_wheel
      displayName: 'Build Python package'

    - task: Docker@2
      displayName: Login of Dockerhub
      inputs:
        command: login
        containerRegistry: Dockerhub-fyc
  
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: yuchen/forecaster
        dockerfile: docker/forecaster.Dockerfile
        containerRegistry: MSRShare
        buildContext: $(System.DefaultWorkingDirectory)
        tags: |
          sing
          $(VERSION)
  
    - script: docker tag japanv100cr.azurecr.io/yuchen/forecaster:$(VERSION) arthurnull/seqml-base:$(VERSION)
      displayName: 'Retag the image'

    - script: docker tag japanv100cr.azurecr.io/yuchen/forecaster:sing arthurnull/seqml-base:latest
      displayName: 'Retag the image'
  
    - task: Docker@2
      displayName: push to Dockerhub
      inputs:
        command: push
        repository: arthurnull/seqml-base
        containerRegistry: Dockerhub-fyc
        tags: |
          latest
          $(VERSION)

    - task: Docker@2
      displayName: Logout of Dockerhub
      inputs:
        command: logout
        containerRegistry: Dockerhub-fyc
